### Part 1
 
---

Running numpy on GPU, with some nice helper functions.

GPU responsible for small calculations, have a lot more cores than CPU

CPU responsible for large calcultions

In [4]:
import torch

x = torch.Tensor([3,5])
y = torch.Tensor([2,1])
print(x*y)

tensor([6., 5.])


In [7]:
x = torch.zeros([3,1])
x

tensor([[0.],
        [0.],
        [0.]])

In [8]:
x.shape

torch.Size([3, 1])

In [9]:
y = torch.rand([2,5])
y

tensor([[0.7524, 0.5043, 0.8880, 0.2174, 0.9088],
        [0.7791, 0.2414, 0.6801, 0.1469, 0.4069]])

Reshape: flatten the array

In [12]:
y = y.view([1,10])
y

tensor([[0.7524, 0.5043, 0.8880, 0.2174, 0.9088, 0.7791, 0.2414, 0.6801, 0.1469,
         0.4069]])

### Part 2: Data
---

- Is the data machine-learnable?
- 90% of time is spent on data collection
- Vision is the main interest

- Training and testing data sets

> hi

In [14]:
import torchvision
from torchvision import transforms, datasets

In [17]:
train = datasets.MNIST("", train=True, download=True, 
                      transform = transforms.Compose([transforms.ToTensor()]))
test = datasets.MNIST("", train=False, download=True, 
                      transform = transforms.Compose([transforms.ToTensor()]))

8:00

In [19]:
test

Dataset MNIST
    Number of datapoints: 10000
    Root location: 
    Split: Test
    StandardTransform
Transform: Compose(
               ToTensor()
           )